server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
      gateway:
        routes:
          #netty 路由过滤器，http或https开头
        - id: app1-route
          uri: http://www.baidu.com
          predicates:
          - Path=/app1/**
          filters:
            #转发请求时去掉1级前缀
          - StripPrefix=1

logging:
  file: ${spring.application.name}.log
  level:
    root: info