server:
  port: 18083

spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuwenjin/config-repo-xwj
  security:
    user:
      name: user
      password: 111